/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        noto: ["'Noto Serif JP', serif"],
        poiret: ["'Poiret One', cursive"],
        tangerine: ["'Tangerine', cursive"],
        sans: ["'PT Sans Narrow', sans-serif"],
        open: ["'Open Sans', sans-serif"],
      },
      backgroundImage: {
        service1: 'url("./Images/suehiro1.jpg")',
        // logo: 'url("./Images/Kauai Tea Ceremony logo.png")',
        communityOutreach: 'url("./Images/communityOutreach12.png")',
        contact: 'url("./Images/contact5.png")',
        product1: 'url("./Images/1000001554.jpg")',
        bowls: 'url("./Images/bowls.png")',
        cupsPlates: 'url("./Images/CupsPlates.png")',
        fabric: 'url("./Images/fabric.png")',
        pot: 'url("./Images/pot.png")',
        placeMats: 'url("./Images/placeMats.png")',
        missionImg: 'url("./Images/1000001568.jpg")',
        history: 'url("./Images/suehiro logo (5).png")',
        history1: 'url("./Images/history1.jpg")',
        retreat: 'url("./Images/retreat2.png")',
        retreat2: 'url("./Images/retreat2.png")',
        retreatVideo: 'url("./Images/retreatVid.mp4")',
        retreatVideo2: 'url("./Images/retreatVid2.mp4")',
        service2: 'url("./Images/suehiroclass2.jpeg")',
        service3: 'url("./Images/suehiroclass2.jpeg")',
        service4: 'url("./Images/suehirokids1.jpg")',
        specialEvents: 'url("./Images/specialEvents.png")',
        tea: 'url("./Images/tea.png")',
        wedding3: 'url("./Images/wedding3.png")',
        wedding1: 'url("./Images/wedding1.png")',
        wedding2: 'url("./Images/wedding2.jpg")',
        wedding4: 'url("./Images/wedding4.png")',
        wedding5: 'url("./Images/wedding5.png")',
        wedding6: 'url("./Images/wedding6.png")',
        wedding7: 'url("./Images/wedding7.png")',
        wedding8: 'url("./Images/wedding4.png")',
        weddingVideo: 'url("./Images/Video Dec 29 2022, 3 49 57 PM.mov")',
        weddingVideo2: 'url("./Images/weddingVideo3.mov")',
        midline: 'url("./Images/midline.png")',
        yukata: 'url("./Images/yukata.png")',
        yukata2: 'url("./Images/yukata2.png")',
        workshop: 'url("./Images/workshop.png")',
        workshop4: 'url("./Images/workshop4.png")',
        hometest: 'url("./Images/hometest.png")',
        hometest2: 'url("./Images/hometest2.jpg")',
        hometest3: 'url("./Images/hometest3.jpg")',
      },
    },
  },
  plugins: [],
};
